- src/pages/index.tsx
Signed-off-by: Ross Turk <ross@rossturk.com>
Thanks @phixMe and @wslulciuc for spotting this and suggesting the solution!
> Order the homepage blogs by date in descending order

- contents/blog/explore-lineage-api/index.mdx
At some point before I merged my code changes, I changed these field names, but never updated the blog 🤦🏽‍♂️
> Update fields in lineage blog to use correct names

- contents/blog/0.1-release/index.mdx
Signed-off-by: Ross Turk <ross@rossturk.com>
> Fix link for astronomer

- contents/blog/dbt-with-marquez/index.mdx
After publishing the blog on dbt, I realized that a few important links were missing (and one was broken!)
Signed-off-by: Ross Turk <ross@rossturk.com>
> Adding some important links to the dbt blog

- contents/integration/dbt/index.mdx
- gatsby-config.ts
- schema.json
- src/style/index.css
- src/templates/basepages.tsx
- src/templates/integration-list.tsx
* increase base font size
* fix responsiveness issues with basepages & integrations
* link from the integrations page to the new dbt blog
* restore overflow-x to code blocks so they can scroll horizontally with long lines
> Collection of small look & feel fixes

- contents/integration/apache-airflow/index.mdx
- src/components/item-integration.tsx
Signed-off-by: John Thomas <john@datakin.com>
> Update Airflow for 2.0+ support, clean up integrations table 

- contents/integration/apache-spark/index.mdx
Recent changes to OpenLineage has resulted in better support for Azure services including: Blob Storage, Data Lake Gen2, and Azure Synapse.
> Include reference to Azure services

- src/style/index.css
Signed-off-by: Ross Turk <ross@datakin.com>
We should be using padding here, not margin.
> Fix image padding

- src/components/layout.tsx
Signed-off-by: Ross Turk <ross.turk@astronomer.io>
This implements Plausible Analytics as an alternative to GA. If this works out, we should disable GA in a future PR.
> Implement Plausible Analytics

- contents/blog/column-lineage/index.mdx
The pub date on the post is incorrect.
> [BLOG] update pub date on lineage post

- contents/basepages/ecosystem/index.mdx
MANTA requested we use a different link to them on the Ecosystem page, so this changes the link there.
Signed-off-by: Michael Robinson <merobi@gmail.com>
> [Basepages] change MANTA link on ecosystem page

- .github/workflows/deploy.yml
- .github/workflows/test-deploy.yml
- README.md
- package.json
- schema.json
- scripts/build-docs.sh
- static/.gitignore
- static/spec/1-0-0/OpenLineage.json
- static/spec/1-0-1/OpenLineage.json
- static/spec/1-0-2/OpenLineage.json
- static/spec/OpenLineage.yml
- static/spec/facets/1-0-0/ColumnLineageDatasetFacet.json
- yarn.lock
This PR does two things:
1) automatically generate apidocs using `redoc-cli` upon site build
2) adds GitHub action to automatically build site and put into `gh-pages` branch
> Automatically generate API docs and site on merge to main

- config.ts
- schema.json
- src/components/__generated__/FooterLinksQuery.d.ts
- src/components/footer.tsx
Signed-off-by: Ross Turk <ross.turk@astronomer.io>
This adds the following to the footer for verification:
`<a rel="me" href="https://fosstodon.org/@openlineage">Mastodon</a>`
Note: merge #84 first!!
> Add mastadon link to footer for verification

- README.md
Signed-off-by: Ross Turk <ross.turk@astronomer.io>
Now that we have website CI working, it occurs to me that the knowledge of how it works is spread across many issues and PRs.
This attempts to document my understanding of:
1. how the website gets built
2. what it is composed of
3. how specs get published
> Document website build & spec generation

- contents/blog/data-lineage-meetup/index.mdx
This adds detail to the directions in the meetup post.
> update directions in meetup post

- contents/blog/data-lineage-meetup/index.mdx
This adds maps and info about the early arrivers' meetup spot to the post.
> add early meetup spot and maps to meetup post

- contents/blog/data-lineage-meetup/index.mdx
This fixes a minor wording issue in the post.
> fix wording in meetup post

- contents/blog/data-lineage-meetup/index.mdx
Adds a link to the meetup.com event.
> edit first meetup post

- contents/blog/data-council-meetup/index.mdx
This updates the Data Council meetup blog post with the latest info about the venue from Missy Bass.
> update meetup details

- contents/blog/data-council-meetup/index.mdx
The blog post about the Data Council Austin meetup needs updating now that the room has been changed.
> update meetup room
